sudo: required
services:
  - docker

before_install:
  - docker build -t di118/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true di118/react-test npm run test

after_success:
  - docker build -t di118/multi-client ./client
  - docker build -t di118/multi-nginx ./nginx
  - docker build -t di118/multi-server ./server
  - docker build -t di118/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push di118/multi-client
  - docker push di118/multi-nginx
  - docker push di118/multi-server
  - docker push di118/multi-worker

deploy:
  provide: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-eu-west-1-074625319160
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
